const SYMS=[['TQQQ',3],['QQQ',1],['TMF',3],['NVDA',1],['VOO',1],['AAPL',1],['V',1]];
async function hist(sym){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${sym}?range=10y&interval=1d&events=div%7Csplit&includeAdjustedClose=true`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(`${sym} yahoo ${r.status}`);const j=await r.json();const x=j.chart?.result?.[0];const raw=x?.indicators?.quote?.[0]?.close||[];const adj=x?.indicators?.adjclose?.[0]?.adjclose||raw;return (x?.timestamp||[]).map((t,i)=>({t,c:adj[i]??raw[i]})).filter(x=>Number.isFinite(x.c));}
function sma(a,n,i){if(i<n-1)return null;let s=0;for(let k=i-n+1;k<=i;k++)s+=a[k].c;return s/n}
function high(a,n,i){if(i<n)return null;let h=-Infinity;for(let k=i-n;k<i;k++)h=Math.max(h,a[k].c);return h}
function dd(eq){let peak=eq[0]||1,m=0;for(const v of eq){peak=Math.max(peak,v);m=Math.min(m,v/peak-1)}return m}
function stats(eq,trades,start,end,addonStops=0){const yrs=(end-start)/(365.25*86400);const fin=eq.at(-1),cagr=Math.pow(fin/10000,1/yrs)-1;const wins=trades.filter(x=>x>0).length;return{final:+fin.toFixed(2),total:+(fin/10000-1).toFixed(4),cagr:+cagr.toFixed(4),mdd:+dd(eq).toFixed(4),roundTrips:trades.length,winRate:trades.length?+(wins/trades.length).toFixed(3):0,addonStops};}
function oldBT(a,lev){let cash=10000,sh=0,lots=[],peak=0,entryEquity=0,eq=[],tr=[];const step=.04*lev,stop=.06*lev,trail=.15*lev;for(let i=200;i<a.length;i++){const p=a[i].c,ma=sma(a,200,i),hh=high(a,40,i);if(!sh&&p>ma&&p>hh){entryEquity=cash;const amt=cash*.4;sh+=amt/p;cash-=amt;lots=[{p,amt}];peak=p;}else if(sh){peak=Math.max(peak,p);if(lots.length<3&&p>=lots.at(-1).p*(1+step)){const amt=Math.min(entryEquity*.3,cash);sh+=amt/p;cash-=amt;lots.push({p,amt});}const avg=lots.reduce((s,x)=>s+x.amt,0)/lots.reduce((s,x)=>s+x.amt/x.p,0);const sell=Math.max(avg*(1-stop),peak*(1-trail));if(p<=sell){const val=cash+sh*p;tr.push(val/entryEquity-1);cash=val;sh=0;lots=[];peak=0;}}eq.push(cash+sh*p);}return stats(eq,tr,a[200].t,a.at(-1).t);}
function bBT(a,lev){let cash=10000,core=null,addons=[],peak=0,entryEquity=0,eq=[],tr=[],addonStops=0,lastBreakout=-1;const stop=.06*lev,trail=.15*lev;for(let i=200;i<a.length;i++){const p=a[i].c,ma=sma(a,200,i),hh=high(a,40,i),br=p>hh;if(!core&&p>ma&&br){entryEquity=cash;const amt=cash*.4;core={shares:amt/p,cost:amt,entry:p};cash-=amt;peak=p;addons=[];lastBreakout=i;}else if(core){peak=Math.max(peak,p);
// Add-on lots are tactical: each gets its own stop; core is not sold when an add-on fails.
for(let z=addons.length-1;z>=0;z--){const L=addons[z];if(p<=L.entry*(1-stop)){cash+=L.shares*p;addons.splice(z,1);addonStops++;}}
// A new confirmed 40-day breakout can refill up to two tactical add-on slots. Same-day entry breakout cannot add.
if(br&&i>lastBreakout&&addons.length<2){const amt=Math.min(entryEquity*.3,cash);if(amt>0){addons.push({shares:amt/p,cost:amt,entry:p});cash-=amt;}lastBreakout=i;}
// Core exit: trailing protection from highest confirmed close, plus original core stop. High-water line never falls.
const coreSell=Math.max(core.entry*(1-stop),peak*(1-trail));if(p<=coreSell){let val=cash+core.shares*p;for(const L of addons)val+=L.shares*p;tr.push(val/entryEquity-1);cash=val;core=null;addons=[];peak=0;}}
let v=cash+(core?core.shares*p:0);for(const L of addons)v+=L.shares*p;eq.push(v);}return stats(eq,tr,a[200].t,a.at(-1).t,addonStops);}
export default async function handler(req,res){try{const out=[];for(const[s,l]of SYMS){const a=await hist(s);const old=oldBT(a,l),b=bBT(a,l);out.push({symbol:s,leverage:l,from:new Date(a[200].t*1000).toISOString().slice(0,10),to:new Date(a.at(-1).t*1000).toISOString().slice(0,10),old,b,delta:{cagr:+(b.cagr-old.cagr).toFixed(4),mdd:+(b.mdd-old.mdd).toFixed(4),total:+(b.total-old.total).toFixed(4)}});}res.setHeader('Cache-Control','no-store');res.status(200).json({assumptions:{capital:10000,period:'10y Yahoo daily adjusted close; warmup 200 trading days',execution:'signal-day adjusted close, fractional shares, no tax/fees/slippage',old:'40% entry on close>MA200 & prior40 high; +30% at +4%*lev, +30% again; all-out at max(weighted avg stop 6%*lev, peak close trail 15%*lev)',B:'40% core on same entry; up to two 30% tactical add-ons on subsequent confirmed prior40-day breakouts; each add-on stops independently at -6%*lev; stopped add-on may only refill on a later new 40-day breakout; core exits at max(core entry stop, peak close trail); add-on failure never lowers core exit'},results:out});}catch(e){res.status(500).json({error:String(e?.stack||e)})}}
